[features]
resolution = true
skip-lint = false

[programs.localnet]
ahorro = "Ez7nS3RhjdeYknDMJSrunJE1wbACMg7yN4YTgFmkHkQz"

[programs.devnet]
ahorro = "Ez7nS3RhjdeYknDMJSrunJE1wbACMg7yN4YTgFmkHkQz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
